# Generated by Django 5.1.5 on 2025-02-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='', height_field='300', null=True, upload_to='photos/usersProfile/<django.db.models.fields.CharField>', width_field='300'),
        ),
    ]
