# Generated by Django 5.1.5 on 2025-02-10 16:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='photos/blanck.png', upload_to=accounts.models.to_path),
        ),
    ]
