# Generated by Django 5.1.5 on 2025-02-11 04:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='photos/blank.jpeg', null=True, upload_to=accounts.models.to_path),
        ),
    ]
